### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by robertlugg** [oysteijo/c_npy#15]
Hi, I'd like to use your code.  I assume its OK to use since you put it on github, but would you be willing to specify a usage license?

**Comment by oysteijo** [comment]
Hi Robert!

Thanks for your suggestion. Of course it is OK to use the code. Of course I will add a license. Hmmm... the only problem is I then have to choose a license. I really don't know which one to pick. I guess I will publish under GPL3 if you do not convince me to use somehting else.

-Øystein

**Comment by oysteijo** [comment]
Browsing my code a bit.... I see that `dostime.[ch]` is actually not my code and `crc32.[ch]` is also not mine. Dostime translation unit is probably taken from a zip library, and the license is kept in the header of the files. CRC32 translation unit is taken from Rosetta code web page. I consider that PD.

Does these observations limit my choice of license?

**Comment by robertlugg** [comment]
Looks like one is GPL and the other is GPL for documentation.  For you putting your code as GPL may make most sense just to make it easier.  My work is closed source which will limit my usage, but that's OK.

**Comment by t-b** [comment]
I'm not sure that a copyleft license like GPL is the right choice for a basic library like this. I would prefer a permissive license like BSD/MIT/etc. So that the code can also be used in closed source software.

**Comment by oysteijo** [comment]
@t-b LGPL also allows linking in the library to non-GPL'ed software even commercial and proprietary codes.  I think that is my first choice. I'll think a bit further of this. If I don't find any more pros and cons, I think it will be LGPL. :-)

**Comment by robertlugg** [comment]
Any of those make sense to me.

**Comment by oysteijo** [comment]
BSD 3-clause it will be. working on it ...

**Comment by oysteijo** [comment]
Closed by Pull Request #21
